-- fortunes 테이블 생성
CREATE DATABASE IF NOT EXISTS fortunes;
USE fortunes;

CREATE TABLE IF NOT EXISTS fortunes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
